export const CITIES = [
  'Warszawa',
  'Kraków',
  'Łódź',
  'Wrocław',
  'Poznań',
  'Gdańsk',
  'Szczecin',
  'Bydgoszcz',
  'Lublin',
  'Białystok',
  'Katowice',
  'Gdynia',
  'Częstochowa',
  'Radom',
  'Rzeszów',
  'Toruń',
  'Sosnowiec',
  'Kielce',
  'Gliwice',
  'Zabrze',
  'Bielsko-Biała',
  'Bytom',
  'Zielona Góra',
  'Rybnik',
  'Ruda Śląska',
  'Opole',
  'Tychy',
  'Gorzów Wielkopolski',
  'Elbląg',
  'Płock',
  'Dąbrowa Górnicza',
  'Wałbrzych',
  'Włocławek',
  'Tarnów',
  'Chorzów',
  'Koszalin',
  'Kalisz',
  'Legnica',
  'Grudziądz',
  'Jaworzno',
  'Słupsk',
  'Jastrzębie-Zdrój',
  'Nowy Sącz',
  'Jelenia Góra',
  'Siedlce',
  'Mysłowice',
  'Piła',
  'Konin',
  'Piotrków Trybunalski',
  'Lubin',
  'Ostrów Wielkopolski',
  'Inowrocław',
  'Suwałki',
  'Stargard',
  'Gniezno',
  'Ostrowiec Świętokrzyski',
  'Siemianowice Śląskie',
  'Głogów',
  'Pabianice',
  'Żory',
  'Pruszków',
  'Leszno',
  'Zamość',
  'Łomża',
  'Tarnowskie Góry',
  'Ełk',
  'Tomaszów Mazowiecki',
  'Chełm',
  'Mielec',
  'Kędzierzyn-Koźle',
  'Przemyśl',
  'Tczew',
  'Stalowa Wola',
  'Biała Podlaska',
  'Bełchatów',
  'Świdnica',
  'Będzin',
  'Zgierz',
  'Piekary Śląskie',
  'Racibórz',
  'Legionowo',
  'Ostrołęka',
  'Rumia',
  'Świętochłowice',
  'Wejherowo',
  'Piaseczno',
  'Zawiercie',
  'Skierniewice',
  'Wodzisław Śląski',
  'Starachowice',
  'Starogard Gdański',
  'Puławy',
  'Tarnobrzeg',
  'Kołobrzeg',
  'Krosno',
  'Radomsko',
  'Dębica',
  'Otwock',
  'Skarżysko-Kamienna',
  'Ciechanów',
  'Nysa',
  'Kutno',
  'Sieradz',
  'Zduńska Wola',
  'Mikołów',
  'Mińsk Mazowiecki',
  'Świnoujście',
  'Szczecinek',
  'Chojnice',
  'Żyrardów',
  'Ząbki',
  'Świdnik',
  'Bolesławiec',
  'Kwidzyn',
  'Nowa Sól',
  'Malbork',
  'Knurów',
  'Marki',
  'Oświęcim',
  'Jarosław',
  'Żary',
  'Sanok',
  'Wołomin',
  'Chrzanów',
  'Czechowice-Dziedzice',
  'Sochaczew',
  'Sopot',
  'Brzeg',
  'Lębork',
  'Olkusz',
  'Jasło',
  'Cieszyn',
  'Kraśnik',
  'Nowy Targ',
  'Iława',
  'Oława',
  'Dzierżoniów',
  'Grodzisk Mazowiecki',
  'Ostróda',
  'Police',
  'Luboń',
  'Pruszcz Gdański',
  'Mława',
  'Myszków',
  'Września',
  'Czeladź',
  'Żywiec',
  'Augustów',
  'Swarzędz',
  'Zgorzelec',
  'Bochnia',
  'Bielawa',
  'Łuków',
  'Śrem',
  'Giżycko',
  'Brodnica',
  'Nowy Dwór Mazowiecki',
  'Krotoszyn',
  'Czerwionka-Leszczyny',
  'Łowicz',
  'Wyszków',
  'Reda',
  'Gorlice',
  'Zakopane',
  'Kętrzyn',
  'Jarocin',
  'Turek',
  'Kłodzko',
  'Biłgoraj',
  'Pszczyna',
  'Kobyłka',
  'Wągrowiec',
  'Świecie',
  'Żagań',
  'Bielsk Podlaski',
  'Wałcz',
  'Wieliczka',
  'Skawina',
  'Białogard',
  'Kościerzyna',
  'Środa Wielkopolska',
  'Kościan',
  'Lubliniec',
  'Kluczbork',
  'Sandomierz',
  'Bartoszyce',
  'Szczytno',
  'Świebodzice',
  'Piastów',
  'Polkowice',
  'Jawor',
  'Ostrów Mazowiecka',
  'Łaziska Górne',
  'Goleniów',
  'Zambrów',
  'Płońsk',
  'Aleksandrów Łódzki',
  'Wieluń',
  'Grajewo',
  'Lubartów',
  'Świebodzin',
  'Nowa Ruda',
  'Orzesze',
  'Rydułtowy',
  'Mrągowo',
  'Koło',
  'Działdowo',
  'Gryfino',
  'Lubań',
  'Opoczno',
  'Prudnik',
  'Hajnówka',
  'Gostyń',
  'Rawicz',
  'Sulejówek',
  'Andrychów',
  'Trzebinia',
  'Bieruń',
  'Pułtusk',
  'Chełmno',
  'Ozorków',
  'Pisz',
  'Sokołów Podlaski',
  'Końskie',
  'Szamotuły',
  'Tomaszów Lubelski',
  'Łęczna',
  'Kamienna Góra',
  'Konstantynów Łódzki',
  'Złotów',
  'Kęty',
  'Pyskowice',
  'Myślenice',
  'Gostynin',
  'Krasnystaw',
  'Wadowice',
  'Chodzież',
  'Nakło nad Notecią',
  'Sokółka',
  'Oborniki',
  'Pionki',
  'Sierpc',
  'Kostrzyn nad Odrą',
  'Łańcut',
  'Międzyrzecz',
  'Radlin',
  'Garwolin',
  'Strzelce Opolskie',
  'Zielonka',
  'Rawa Mazowiecka',
  'Łomianki',
  'Hrubieszów',
  'Przasnysz',
  'Trzcianka',
  'Bogatynia',
  'Braniewo',
  'Radzionków',
  'Pleszew',
  'Łask',
  'Konstancin-Jeziorna',
  'Bytów',
  'Libiąż',
  'Kozienice',
  'Lędziny',
  'Grójec',
  'Brzesko',
  'Namysłów',
  'Międzyrzec Podlaski',
  'Słubice',
  'Milanówek',
  'Sulechów',
  'Gubin',
  'Nowogard',
  'Olecko',
  'Gryfice',
  'Ustroń',
  'Rypin',
  'Krapkowice',
  'Ropczyce',
  'Strzegom',
  'Dęblin',
  'Solec Kujawski',
  'Jelcz-Laskowice',
  'Busko-Zdrój',
  'Lidzbark Warmiński',
  'Łapy',
  'Radzyń Podlaski',
  'Świdwin',
  'Nisko',
  'Złotoryja',
  'Boguszów-Gorce',
  'Ustka',
  'Limanowa',
  'Przeworsk',
  'Choszczno',
  'Jędrzejów',
  'Grodzisk Wielkopolski',
  'Ząbkowice Śląskie',
  'Staszów',
  'Niepołomice',
  'Chełmża',
  'Mosina',
  'Lipno',
  'Kartuzy',
  'Nowy Tomyśl',
  'Siemiatycze',
  'Skoczów',
  'Ostrzeszów',
  'Głowno',
  'Kępno',
  'Brwinów',
  'Pszów',
  'Łęczyca',
  'Lubsko',
  'Wschowa',
  'Gołdap',
  'Barlinek',
  'Dębno',
  'Słupca',
  'Tuchola',
  'Leżajsk',
  'Żnin',
  'Darłowo',
  'Nidzica',
  'Radzymin',
  'Człuchów',
  'Trzebnica',
  'Wąbrzeźno',
  'Morąg',
  'Głuchołazy',
  'Chojnów',
  'Włodawa',
  'Wolsztyn',
  'Koluszki',
  'Kłobuck',
  'Ożarów Mazowiecki',
  'Złocieniec',
  'Rabka-Zdrój',
  'Brzeg Dolny',
  'Pyrzyce',
  'Węgrów',
  'Sędziszów Małopolski',
  'Strzelin',
  'Głubczyce',
  'Brzeziny',
  'Golub-Dobrzyń',
  'Sławno',
  'Wołów',
  'Pasłęk',
  'Błonie',
  'Aleksandrów Kujawski',
  'Góra Kalwaria',
  'Warka',
  'Wasilków',
  'Dąbrowa Tarnowska',
  'Lubaczów',
  'Janów Lubelski',
  'Mogilno',
  'Góra',
  'Szydłowiec',
  'Szprotawa',
  'Miechów',
  'Drawsko Pomorskie',
  'Zdzieszowice',
  'Węgorzewo',
  'Milicz',
  'Puck',
  'Krosno Odrzańskie',
  'Rogoźno',
  'Myślibórz',
  'Koronowo',
  'Brzeszcze',
  'Wronki',
  'Nowa Dęba',
  'Wisła',
  'Nowe Miasto Lubawskie',
  'Biskupiec',
  'Kowary',
  'Ciechocinek',
  'Parczew',
  'Międzychód',
  'Pińczów',
  'Murowana Goślina',
  'Czarnków',
  'Lubawa',
  'Krynica-Zdrój',
  'Syców',
  'Miastko',
  'Kolno',
  'Łobez',
  'Krzeszowice',
  'Dobre Miasto',
  'Sulęcin',
  'Bukowno',
  'Mońki',
  'Drezdenko',
  'Czersk',
  'Trzebiatów',
  'Głogów Małopolski',
  'Władysławowo',
  'Nowy Dwór Gdański',
  'Bystrzyca Kłodzka',
  'Strzelce Krajeńskie',
  'Karczew',
  'Sztum',
  'Włoszczowa',
  'Kudowa-Zdrój',
  'Kostrzyn',
  'Szubin',
  'Środa Śląska',
  'Maków Mazowiecki',
  'Puszczykowo',
  'Ryki',
  'Opalenica',
  'Pobiedziska',
  'Blachownia',
  'Skwierzyna',
  'Olesno',
  'Imielin',
  'Wysokie Mazowieckie',
  'Kruszwica',
  'Kożuchów',
  'Czarna Białostocka',
  'Siechnice',
  'Oborniki Śląskie',
  'Sucha Beskidzka',
  'Stary Sącz',
  'Sępólno Krajeńskie',
  'Poniatowa',
  'Kolbuszowa',
  'Wojkowice',
  'Chełmek',
  'Ustrzyki Dolne',
  'Strzyżów',
  'Żuromin',
  'Lwówek Śląski',
  'Kamień Pomorski',
  'Orneta',
  'Janikowo',
  'Prabuty',
  'Jastrowie',
  'Kalety',
  'Ziębice',
  'Grodków',
  'Wolbrom',
  'Ozimek',
  'Poręba',
  'Wieruszów',
  'Opole Lubelskie',
  'Suchedniów',
  'Tłuszcz',
  'Pniewy',
  'Kórnik',
  'Połczyn-Zdrój',
  'Połaniec',
  'Żychlin',
  'Mszana Dolna',
  'Chocianów',
  'Witkowo',
  'Zwoleń',
  'Nasielsk',
  'Lidzbark',
  'Trzemeszno',
  'Pelplin',
  'Barczewo',
  'Olsztynek',
  'Praszka',
  'Zelów',
  'Brzozów',
  'Miasteczko Śląskie',
  'Chojna',
  'Paczków',
  'Barcin',
  'Tuszyn',
  'Poddębice',
  'Zbąszyń',
  'Kąty Wrocławskie',
  'Czaplinek',
  'Gniewkowo',
  'Łosice',
  'Zawadzkie',
  'Skarszewy',
  'Pieszyce',
  'Sławków',
  'Sobótka',
  'Białobrzegi',
  'Łochów',
  'Gogolin',
  'Żukowo',
  'Łazy',
  'Rudnik nad Sanem',
  'Sułkowice',
  'Witnica',
  'Żarów',
  'Pajęczno',
  'Szklarska Poręba',
  'Gniew',
  'Twardogóra',
  'Sianów',
  'Gryfów Śląski',
  'Tuchów',
  'Rzepin',
  'Otmuchów',
  'Żmigród',
  'Dobczyce',
  'Koźmin Wielkopolski',
  'Bełżyce',
  'Piława Górna',
  'Opatów',
  'Sędziszów',
  'Kłodawa',
  'Mszczonów',
  'Głuszyca',
  'Polanica-Zdrój',
  'Boguchwała',
  'Niemodlin',
  'Sulejów',
  'Krzyż Wielkopolski',
  'Dynów',
  'Przemków',
  'Piechowice',
  'Choroszcz',
  'Grybów',
  'Buk',
  'Proszowice',
  'Sieraków',
  'Stęszew',
  'Lubawka',
  'Więcbork',
  'Kietrz',
  'Karlino',
  'Czarne',
  'Koniecpol',
  'Piwniczna-Zdrój',
  'Wołczyn',
  'Maków Podhalański',
  'Przysucha',
  'Pieńsk',
  'Nowa Sarzyna',
  'Wieleń',
  'Działoszyn',
  'Nowe',
  'Szczyrk',
  'Lewin Brzeski',
  'Jedlicze',
  'Szczawnica',
  'Śmigiel',
  'Stronie Śląskie',
  'Pakość',
  'Siewierz',
  'Strzelno',
  'Głogówek',
  'Ścinawa',
  'Stąporków',
  'Susz',
  'Orzysz',
  'Szczawno-Zdrój',
  'Radziejów',
  'Terespol',
  'Lądek-Zdrój',
  'Kazimierza Wielka',
  'Lesko',
  'Lipsko',
  'Dąbrowa Białostocka',
  'Dzierzgoń',
  'Międzyzdroje',
  'Brusy',
  'Kuźnia Raciborska',
  'Radymno',
  'Jordanów',
  'Sejny',
  'Jaworzyna Śląska',
  'Wyrzysk',
  'Odolanów',
  'Zagórz',
  'Nowogród Bobrzański',
  'Debrzno',
  'Szczytna',
  'Borne Sulinowo',
  'Zbąszynek',
  'Pilzno',
  'Czempiń',
  'Szczebrzeszyn',
  'Bolków',
  'Bierutów',
  'Łaskarzew',
  'Bychawa',
  'Jedlina-Zdrój',
  'Wolin',
  'Nowe Skalmierzyce',
  'Muszyna',
  'Serock',
  'Iłża',
  'Supraśl',
  'Pilawa',
  'Brześć Kujawski',
  'Ciechanowiec',
  'Żarki',
  'Biecz',
  'Skoki',
  'Reszel',
  'Kamieniec Ząbkowicki',
  'Budzyń',
  'Łabiszyn',
  'Kcynia',
  'Kalwaria Zebrzydowska',
  'Golina',
  'Zduny',
  'Karpacz',
  'Ożarów',
  'Ruciane-Nida',
  'Chęciny',
  'Duszniki-Zdrój',
  'Piotrków Kujawski',
  'Kalisz Pomorski',
  'Raciąż',
  'Leśna',
  'Krobia',
  'Krzepice',
  'Skaryszew',
  'Olszyna',
  'Rejowiec Fabryczny',
  'Woźniki',
  'Mrocza',
  'Słomniki',
  'Nowogrodziec',
  'Sława',
  'Bytom Odrzański',
  'Krośniewice',
  'Sokołów Małopolski',
  'Ogrodzieniec',
  'Szamocin',
  'Nowy Staw',
  'Jasień',
  'Tarczyn',
  'Żabno',
  'Szczucin',
  'Resko',
  'Korsze',
  'Zawidów',
  'Kowalewo Pomorskie',
  'Kleczew',
  'Gąbin',
  'Biała Piska',
  'Tyczyn',
  'Tułowice',
  'Jedlnia-Letnisko',
  'Świeradów-Zdrój',
  'Bobolice',
  'Mieroszów',
  'Czerwieńsk',
  'Płoty',
  'Ośno Lubuskie',
  'Żelechów',
  'Lipiany',
  'Janowiec Wielkopolski',
  'Babimost',
  'Nekla',
  'Górowo Iławeckie',
  'Iłowa',
  'Okonek',
  'Podkowa Leśna',
  'Drzewica',
  'Kargowa',
  'Mirsk',
  'Rymanów',
  'Skała',
  'Pruchnik',
  'Mikołajki',
  'Halinów',
  'Nałęczów',
  'Jabłonowo Pomorskie',
  'Barwice',
  'Brańsk',
  'Dobrodzień',
  'Nowe Miasto nad Pilicą',
  'Małogoszcz',
  'Strumień',
  'Rakoniewice',
  'Zator',
  'Ujście',
  'Opatówek',
  'Skórcz',
  'Chmielnik',
  'Krajenka',
  'Mrozy',
  'Mieszkowice',
  'Wojcieszów',
  'Toszek',
  'Skępe',
  'Prochowice',
  'Łeba',
  'Kępice',
  'Miłosław',
  'Małomice',
  'Byczyna',
  'Szczekociny',
  'Kowal',
  'Sompolno',
  'Przedbórz',
  'Stryków',
  'Myszyniec',
  'Rzgów',
  'Maszewo',
  'Złoczew',
  'Szczuczyn',
  'Alwernia',
  'Kolonowskie',
  'Wojnicz',
  'Tarnogród',
  'Radomyśl Wielki',
  'Kock',
  'Kobylin',
  'Miejska Górka',
  'Warta',
  'Tuliszków',
  'Hel',
  'Wilamowice',
  'Łasin',
  'Gołańcz',
  'Zakroczym',
  'Bobowa',
  'Biała Rawska',
  'Jeziorany',
  'Chociwel',
  'Kańczuga',
  'Dobrzyca',
  'Ślesin',
  'Zwierzyniec',
  'Chorzele',
  'Pyzdry',
  'Radoszyce',
  'Krasnobród',
  'Mirosławiec',
  'Dobiegniew',
  'Margonin',
  'Ćmielów',
  'Uniejów',
  'Glinojeck',
  'Wielbark',
  'Michałowo',
  'Rydzyna',
  'Gozdnica',
  'Zaklików',
  'Oleszyce',
  'Lwówek',
  'Łobżenica',
  'Niemcza',
  'Lubraniec',
  'Kaczory',
  'Bojanowo',
  'Poniec',
  'Polanów',
  'Zagórów',
  'Kunów',
  'Mielno',
  'Recz',
  'Baborów',
  'Kałuszyn',
  'Daleszyce',
  'Sulmierzyce',
  'Ryglice',
  'Ryn',
  'Węgliniec',
  'Drobin',
  'Cybinka',
  'Czarna Woda',
  'Brzostek',
  'Węgorzyno',
  'Nowy Wiśnicz',
  'Radłów',
  'Nowe Miasteczko',
  'Książ Wielkopolski',
  'Kamieńsk',
  'Wąchock',
  'Knyszyn',
  'Różan',
  'Jastarnia',
  'Golczewo',
  'Złoty Stok',
  'Pruszcz',
  'Pieniężno',
  'Czerniejewo',
  'Wąsosz',
  'Dziwnów',
  'Czyżew',
  'Wysoka',
  'Tolkmicko',
  'Kłecko',
  'Pełczyce',
  'Izbica Kujawska',
  'Prószków',
  'Wyszogród',
  'Leśnica',
  'Kazimierz Dolny',
  'Miłakowo',
  'Torzym',
  'Piaski',
  'Tychowo',
  'Pasym',
  'Międzylesie',
  'Zabłudów',
  'Borek Wielkopolski',
  'Bardo',
  'Stoczek Łukowski',
  'Stepnica',
  'Świątniki Górne',
  'Koziegłowy',
  'Gorzów Śląski',
  'Gościno',
  'Ciężkowice',
  'Koprzywnica',
  'Lubycza Królewska',
  'Annopol',
  'Miłomłyn',
  'Osieczna',
  'Radków',
  'Łęknica',
  'Obrzycko',
  'Biała',
  'Rychwał',
  'Kamień Krajeński',
  'Trzciel',
  'Międzybórz',
  'Czchów',
  'Krynki',
  'Bisztynek',
  'Wolbórz',
  'Człopa',
  'Frombork',
  'Dobra',
  'Chodecz',
  'Lututów',
  'Lipsk',
  'Cegłów',
  'Prusice',
  'Drawno',
  'Biały Bór',
  'Dobrzany',
  'Świerzawa',
  'Trzcińsko-Zdrój',
  'Wiązów',
  'Bodzentyn',
  'Mogielnica',
  'Szepietowo',
  'Nowogród',
  'Błażowa',
  'Suchowola',
  'Stawiski',
  'Sieniawa',
  'Krzanowice',
  'Żerków',
  'Zalewo',
  'Raszków',
  'Pogorzela',
  'Ostrów Lubelski',
  'Łaszczów',
  'Lubniewice',
  'Kosów Lacki',
  'Kisielice',
  'Dobrzyń nad Wisłą',
  'Dukla',
  'Narol',
  'Błaszki',
  'Tyszowce',
  'Rejowiec',
  'Lubomierz',
  'Dąbie',
  'Jutrosin',
  'Tykocin',
  'Osiek',
  'Koźminek',
  'Sośnicowice',
  'Drohiczyn',
  'Ostroróg',
  'Tuczno',
  'Sanniki',
  'Pilica',
  'Sochocin',
  'Grabów nad Prosną',
  'Cieszanów',
  'Szadek',
  'Brok',
  'Ińsko',
  'Sępopol',
  'Klimontów',
  'Bieżuń',
  'Nieszawa',
  'Mikstat',
  'Goniądz',
  'Przecław',
  'Oleśnica',
  'Radzyń Chełmiński',
  'Chocz',
  'Korfantów',
  'Młynary',
  'Wielichowo',
  'Ujazd',
  'Iwonicz-Zdrój',
  'Krzywiń',
  'Wleń',
  'Mordy',
  'Zawichost',
  'Morawica',
  'Kamionka',
  'Piątek',
  'Urzędów',
  'Otyń',
  'Nowe Brzesko',
  'Nowe Miasto',
  'Lubowidz',
  'Zakliczyn',
  'Przedecz',
  'Moryń',
  'Jedwabne',
  'Lutomiersk',
  'Dolsk',
  'Łagów',
  'Rajgród',
  'Cedynia',
  'Modliborzyce',
  'Stawiszyn',
  'Suchań',
  'Frampol',
  'Kołaczyce',
  'Baranów Sandomierski',
  'Ulanów',
  'Stopnica',
  'Górzno',
  'Siedliszcze',
  'Jaraczewo',
  'Lubień Kujawski',
  'Nowa Słupia',
  'Wiskitki',
  'Iwaniska',
  'Krynica Morska',
  'Szlichtyngowa',
  'Skalbmierz',
  'Kleszczele',
  'Nowe Warpno',
  'Pierzchnica',
  'Pacanów',
  'Szydłów',
  'Wodzisław',
  'Czerwińsk nad Wisłą',
  'Suraż',
  'Bolimów',
  'Solec nad Wisłą',
  'Goraj',
  'Nowy Korczyn',
  'Józefów nad Wisłą',
  'Wyśmierzyce',
  'Działoszyce',
  'Dubiecko',
  'Koszyce',
  'Wiślica',
  'Izbica',
  'Opatowiec',
];
